/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static java.lang.System.exit;
import javax.swing.JFrame;
import model.SharedData;

/**
 *
 * @author ndnha
 */
public class MainForm extends javax.swing.JFrame {

    private ShowComponentsPanel mShowComponentPanel;
    private ComponentsManagementPanel mComponentsManagementPanel;
    private AboutUsDialog frmabout;
    private ComponentTypeManagementDialog frmComponentTypeManagement;
    private HintComponentsPanel mHintComponentPanel;
    private LoginDialog frmlogin;
    
    public void setfrmlogin (LoginDialog frm) {
        frmlogin = frm;
    }

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tplMainBoard = new javax.swing.JTabbedPane();
        btnDSLK = new javax.swing.JButton();
        btnQLLK = new javax.swing.JButton();
        btnQLLoaiLK = new javax.swing.JButton();
        btnHint = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        lblLoginName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDSLK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/computercomponents32.png"))); // NOI18N
        btnDSLK.setText("Danh sách linh kiện");
        btnDSLK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDSLK.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDSLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSLKActionPerformed(evt);
            }
        });

        btnQLLK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manage32.png"))); // NOI18N
        btnQLLK.setText("Quản lý linh kiện");
        btnQLLK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLLK.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLLKActionPerformed(evt);
            }
        });

        btnQLLoaiLK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manage32_2.png"))); // NOI18N
        btnQLLoaiLK.setText("Quản lý loại linh kiện");
        btnQLLoaiLK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLLoaiLK.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLLoaiLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLLoaiLKActionPerformed(evt);
            }
        });

        btnHint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/idea32.png"))); // NOI18N
        btnHint.setText("Gợi ý linh kiện theo số tiền");
        btnHint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHintActionPerformed(evt);
            }
        });

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about-32.png"))); // NOI18N
        btnAbout.setText("Giới thiệu");
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout16.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        lblRole.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblLoginName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoginName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(lblLoginName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDangXuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(tplMainBoard))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(117, Short.MAX_VALUE)
                        .addComponent(btnDSLK)
                        .addGap(50, 50, 50)
                        .addComponent(btnQLLK)
                        .addGap(50, 50, 50)
                        .addComponent(btnQLLoaiLK)
                        .addGap(50, 50, 50)
                        .addComponent(btnHint)
                        .addGap(50, 50, 50)
                        .addComponent(btnAbout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnDSLK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQLLoaiLK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQLLK, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAbout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHint, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDSLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSLKActionPerformed
        if (mShowComponentPanel == null) {
            mShowComponentPanel = new ShowComponentsPanel();
            tplMainBoard.addTab("Danh sách Linh kiện", mShowComponentPanel);
        }
        tplMainBoard.setSelectedComponent(mShowComponentPanel);
    }//GEN-LAST:event_btnDSLKActionPerformed

    private void btnQLLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLLKActionPerformed
        if (mComponentsManagementPanel == null) {
            mComponentsManagementPanel = new ComponentsManagementPanel();
            tplMainBoard.addTab("Quản lý Linh Kiện", mComponentsManagementPanel);
        }
        tplMainBoard.setSelectedComponent(mComponentsManagementPanel);
    }//GEN-LAST:event_btnQLLKActionPerformed

    private void btnQLLoaiLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLLoaiLKActionPerformed
        if (frmComponentTypeManagement == null) {
            frmComponentTypeManagement = new ComponentTypeManagementDialog(this, true);
        }
        frmComponentTypeManagement.setVisible(true);
    }//GEN-LAST:event_btnQLLoaiLKActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        if (frmlogin == null) {
            frmlogin = new LoginDialog();
        }
        frmlogin.setVisible(true);
        this.setVisible(false);
        SharedData.nguoiDangNhap = null;
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        if (frmabout == null) {
            frmabout = new AboutUsDialog(this, true);
        }
        frmabout.setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHintActionPerformed
        if (mHintComponentPanel == null) {
            mHintComponentPanel = new HintComponentsPanel();
            tplMainBoard.addTab("Gợi ý Linh kiện theo số tiền", mHintComponentPanel);
        }
        tplMainBoard.setSelectedComponent(mHintComponentPanel);
    }//GEN-LAST:event_btnHintActionPerformed
    
    private void processLoginSuccessful() {
        lblLoginName.setText(SharedData.nguoiDangNhap.getTenDangNhap());
        lblRole.setText("Admin");
    }
    
    private void processLoginCustomer() {
        lblLoginName.setText("Khách hàng ẩn danh");
        lblRole.setText("Khách hàng");
    }
    
    public void phanQuyenNguoiDung() {
        if (SharedData.nguoiDangNhap != null) {
            processLoginSuccessful();
            btnQLLK.setEnabled(true);
            btnQLLoaiLK.setEnabled(true);
        } else {
            processLoginCustomer();
            btnQLLK.setEnabled(false);
            btnQLLoaiLK.setEnabled(false);
            if (mComponentsManagementPanel != null)
                tplMainBoard.remove(tplMainBoard.indexOfComponent(mComponentsManagementPanel));
                mComponentsManagementPanel = null;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnDSLK;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHint;
    private javax.swing.JButton btnQLLK;
    private javax.swing.JButton btnQLLoaiLK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoginName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
